version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
reports:
  test-report:
    files:
      - target/surefire-reports/*.xml
    file-format: JunitXml
artifacts:
  files:
    - target/math-library-1.0.jar
